language: ruby
sudo: required
dist: trusty
rvm:
  - 2.3.5
before_install: gem install bundler -v 1.16.0
before_script:
  - cp config/application.yml.example config/application.yml
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
notifications:
  email:
    - luizpicolo@gmail.com
